# 搭建测试框架

找到一个 autolisp 大牛的相关资料：

[jdsandifer/ALUnit: The only unit testing framework for AutoLISP available on GitHub (as of its publication).](https://github.com/jdsandifer/ALUnit)

[jdsandifer/AutoLISP: Programs written to help drafters work faster and automate common tasks in AutoCAD. (Professional Experience)](https://github.com/jdsandifer/AutoLISP)

[jdsandifer/Reading-List: See if I've read your favorite software development book or get ideas for your next read!](https://github.com/jdsandifer/Reading-List)

fork 了他 2 个仓库，里面的代码值得仔细研读，感觉是个宝藏。

### 2020-10-24

直接用成品「ALUnit」一直没有跑通。幸好在作者的第二个项目仓库「jdsandifer/AutoLISP」里看到一个「TEST.lsp」文件，直接借鉴里面的代码。但作者的 `DL:CountBooleans` 有问题，自己重写后跑通了基本测试。同时把失败案例的提示单独拎出来了。

### 2020-10-26

遇到的一个问题：断言的传参列表里如果还嵌入列表，就有报错。

比如 `(AssertEqual 'GetIndexforSearchMemberInListUtils (list "PL1101" (list "PL1101" "PL1102")) 0)` 报错：`函数错误："PL1101"`。

如果改成 `(AssertEqual 'GetIndexforSearchMemberInListUtils '("PL1101" '("PL1101" "PL1102")) 0)`，跑测试后会出现 `failed...return nil instead of 1` 信息，还是报错 `错误：参数类型错误`。

早上看成品「ALUnit」里「Assert.lsp」的代码，发现一个关键信息：作者用 `vl-catch-all-apply` 取代了原来的 `eval` 函数，原来测试代码里最关键的语句就是：

```c
(equal (setq actualReturn (eval (cons functionName argumentList)))
			  expectedReturn)
```

作者替换成了：

```c
(equal (setq actualReturn (vl-catch-all-apply functionName argumentList))
			  expectedReturn)
```

接着去官方文档了解了下该函数：[vl-catch-all-apply (AutoLISP)](http://help.autodesk.com/view/OARX/2018/CHS/?guid=GUID-E08CC2A6-787A-422F-8BD3-18812996794C)。

Passes a list of arguments to a specified function and traps any exceptions.

```c
(vl-catch-all-apply 'function list)
```

'function. Type: Symbol. A function. The function argument can be either a symbol identifying a defun or lambda expression.

list. Type: List. A list containing arguments to be passed to the function.

Return Values. Type: Integer, Real, String, List, Ename (entity name), T, nil, or catch-all-apply-error.

The result of the function call, if successful. If an error occurs, vl-catch-all-apply returns an error object.

Examples:

If the function invoked by vl-catch-all-apply completes successfully, it is the same as using apply, as the following examples show:

```c
(setq catchit (apply '/ '(50 5)))
10

(setq catchit (vl-catch-all-apply '/ '(50 5)))
10
```

The benefit of using `vl-catch-all-apply` is that it allows you to intercept errors and continue processing. See what happens when you try to divide by zero using apply:

```c
(setq catchit (apply '/ '(50 0)))
; error: divide by zero
```

When you use apply, an exception occurs and an error message displays. Here is the same operation using `vl-catch-all-apply`:

```c
(setq catchit (vl-catch-all-apply '/ '(50 0)))
#<%catch-all-apply-error%>
```

The `vl-catch-all-apply` function traps the error and returns an error object. Use `vl-catch-all-error-message` to see the error message contained in the error object:

```c
(vl-catch-all-error-message catchit)
"divide by zero"
```

1『看到这里基本上也理解了 `apply` 函数的用法，哈哈。（2020-10-26）』

测试框架里用 `vl-catch-all-apply` 重构后，再使用 `(AssertEqual 'GetIndexforSearchMemberInListUtils (list "PL1101" (list "PL1101" "PL1102")) 0)` 跑测试就 OK 了。